// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vigil/VigilCompass.tsx": () => import("../components/mockups/vigil/VigilCompass.tsx")
};
