type SupportedLanguage = 'en' | 'ar' | 'fr' | 'cs' | 'de' | 'es' | 'ru';

const en = {
  onboardingFlowEyebrow: 'YOUR MONEY, YOUR WAY',
  onboardingFlowQuestionProgress: 'Question {current} of {total}',
  onboardingFlowQ1Title: 'What would you most like to change about your money?',
  onboardingFlowQ1Support: 'We’ll personalize Vigil around what matters most to you.',
  onboardingFlowQ1Choices: 'Stop wondering where my money went|Spend less without feeling restricted|Save more consistently|Get control of my finances|Build better money habits',
  onboardingFlowQ2Title: 'What frustrates you most right now?',
  onboardingFlowQ2Choices: 'My money disappears too quickly|I spend more than I realize|Tracking expenses takes too much effort|I struggle to stick to a budget|I know I could save more',
  onboardingFlowQ3Title: 'When you don’t know where your money went, how does it usually make you feel?',
  onboardingFlowQ3Support: 'There’s no right or wrong answer.',
  onboardingFlowQ3Choices: 'Stressed|Frustrated|Guilty|Out of control|I mostly avoid thinking about it',
  onboardingFlowQ4Title: 'How often do you check where your money actually went?',
  onboardingFlowQ4Choices: 'Every day|A few times a week|Occasionally|Usually when money gets tight|Almost never',
  onboardingFlowQ5Title: 'What usually stops you from tracking your spending?',
  onboardingFlowQ5Choices: 'It takes too much time|I forget|I hate entering everything manually|Other apps feel complicated|I start, but don’t stay consistent',
  onboardingFlowQ6Title: 'Imagine knowing exactly where your money goes without constantly thinking about it. What would that give you?',
  onboardingFlowQ6Choices: 'Peace of mind|More savings|More control|Confidence spending money|Progress toward my goals',
  onboardingFlowGoalPhrases: 'stop wondering where my money went|spend less without feeling restricted|save more consistently|get control of my finances|build better money habits',
  onboardingFlowFrictionPhrases: 'tracking expenses takes too much effort|you forget to do it|entering every expense manually feels like too much|other apps feel complicated|it is hard to stay consistent',
  onboardingFlowReliefTitle: 'Vigil can help you get there.',
  onboardingFlowReliefTemplate: 'You told us you want to {goal}, but {friction}. Vigil is designed to make staying on top of your money easier.',
  onboardingFlowReliefBenefitsTitle: 'With Vigil, you can:',
  onboardingFlowReliefBenefit1: 'Capture spending without tedious manual tracking',
  onboardingFlowReliefBenefit2: 'See where your money is actually going',
  onboardingFlowReliefBenefit3: 'Spot spending patterns more easily',
  onboardingFlowReliefBenefit4: 'Plan spending and savings with more confidence',
  onboardingFlowBuildPlan: 'Build my plan',
  onboardingFlowTransition1: 'Understanding your goals…',
  onboardingFlowTransition2: 'Identifying what gets in your way…',
  onboardingFlowTransition3: 'Personalizing your Vigil experience…',
  onboardingFlowResultEyebrow: 'MADE AROUND WHAT YOU SHARED',
  onboardingFlowResultTitle: 'Your Vigil plan is ready.',
  onboardingFlowResultTemplate: 'You want to {goal}, but {friction}. Vigil brings your money tools together in a simpler place to start.',
  onboardingFlowFeatureVoice: 'Voice expense logging',
  onboardingFlowFeatureReceipt: 'Receipt scanning',
  onboardingFlowFeatureBank: 'Bank screenshot importing',
  onboardingFlowFeatureInsights: 'Spending insights',
  onboardingFlowFeaturePlanning: 'Income and spending planning',
  onboardingFlowFeatureReminders: 'Smart reminders',
  onboardingFlowFeatureCurrency: 'Multi-currency tracking',
  onboardingFlowStartTakingControl: 'Start taking control',
  onboardingFlowPaywallHeadline: 'Know where it all goes.',
  onboardingFlowPaywallSupport: 'Start building the money habits you told us you want.',
  onboardingFlowPaywallGoalTemplate: 'Your goal: {goal}',
};

export type OnboardingFlowCopyKey = keyof typeof en;

export const onboardingFlowCopy: Record<SupportedLanguage, Record<OnboardingFlowCopyKey, string>> = {
  en,
  fr: {
    onboardingFlowEyebrow: 'VOTRE ARGENT, À VOTRE FAÇON',
    onboardingFlowQuestionProgress: 'Question {current} sur {total}',
    onboardingFlowQ1Title: 'Qu’aimeriez-vous le plus changer dans votre rapport à l’argent ?',
    onboardingFlowQ1Support: 'Nous adapterons Vigil à ce qui compte le plus pour vous.',
    onboardingFlowQ1Choices: 'Ne plus me demander où passe mon argent|Dépenser moins sans avoir l’impression de me priver|Épargner plus régulièrement|Mieux maîtriser mes finances|Prendre de meilleures habitudes financières',
    onboardingFlowQ2Title: 'Qu’est-ce qui vous frustre le plus en ce moment ?',
    onboardingFlowQ2Choices: 'J’ai l’impression que mon argent part trop vite|Je dépense plus que je ne le pense|Suivre mes dépenses me demande trop d’efforts|J’ai du mal à respecter mon budget|Je sais que je pourrais épargner davantage',
    onboardingFlowQ3Title: 'Quand vous ne savez pas où votre argent est passé, qu’est-ce que vous ressentez le plus souvent ?',
    onboardingFlowQ3Support: 'Il n’y a pas de bonne ou de mauvaise réponse.',
    onboardingFlowQ3Choices: 'Du stress|De la frustration|De la culpabilité|Une perte de contrôle|J’évite généralement d’y penser',
    onboardingFlowQ4Title: 'À quelle fréquence vérifiez-vous où votre argent est vraiment passé ?',
    onboardingFlowQ4Choices: 'Tous les jours|Quelques fois par semaine|De temps en temps|Surtout quand l’argent commence à manquer|Presque jamais',
    onboardingFlowQ5Title: 'Qu’est-ce qui vous empêche généralement de suivre vos dépenses ?',
    onboardingFlowQ5Choices: 'Cela prend trop de temps|J’oublie|Je n’aime pas tout saisir à la main|Les autres applis me semblent compliquées|Je commence, mais j’ai du mal à m’y tenir',
    onboardingFlowQ6Title: 'Imaginez savoir exactement où va votre argent sans y penser constamment. Qu’est-ce que cela vous apporterait ?',
    onboardingFlowQ6Choices: 'La tranquillité d’esprit|Épargner davantage|Plus de contrôle|Dépenser avec confiance|Avancer vers mes objectifs',
    onboardingFlowGoalPhrases: 'ne plus vous demander où passe votre argent|dépenser moins sans avoir l’impression de vous priver|épargner plus régulièrement|mieux maîtriser vos finances|prendre de meilleures habitudes financières',
    onboardingFlowFrictionPhrases: 'suivre vos dépenses vous prend trop de temps|vous oubliez de le faire|saisir chaque dépense à la main vous demande trop d’efforts|les autres applications vous semblent compliquées|vous avez du mal à rester régulier',
    onboardingFlowReliefTitle: 'Vigil peut vous aider à avancer.',
    onboardingFlowReliefTemplate: 'Vous nous avez dit vouloir {goal}, mais {friction}. Vigil est conçu pour vous aider à suivre votre argent plus facilement.',
    onboardingFlowReliefBenefitsTitle: 'Avec Vigil, vous pouvez :',
    onboardingFlowReliefBenefit1: 'Enregistrer vos dépenses sans tout saisir à la main',
    onboardingFlowReliefBenefit2: 'Voir où va réellement votre argent',
    onboardingFlowReliefBenefit3: 'Repérer plus facilement vos habitudes de dépenses',
    onboardingFlowReliefBenefit4: 'Planifier dépenses et épargne avec plus d’assurance',
    onboardingFlowBuildPlan: 'Créer mon plan',
    onboardingFlowTransition1: 'Compréhension de vos objectifs…',
    onboardingFlowTransition2: 'Repérage de ce qui vous freine…',
    onboardingFlowTransition3: 'Personnalisation de votre expérience Vigil…',
    onboardingFlowResultEyebrow: 'SELON CE QUE VOUS NOUS AVEZ DIT',
    onboardingFlowResultTitle: 'Votre plan Vigil est prêt.',
    onboardingFlowResultTemplate: 'Vous souhaitez {goal}, mais {friction}. Vigil rassemble vos outils financiers dans un espace simple pour commencer.',
    onboardingFlowFeatureVoice: 'Saisie des dépenses à la voix',
    onboardingFlowFeatureReceipt: 'Numérisation des reçus',
    onboardingFlowFeatureBank: 'Import de captures d’écran bancaires',
    onboardingFlowFeatureInsights: 'Analyses de vos dépenses',
    onboardingFlowFeaturePlanning: 'Planification des revenus et dépenses',
    onboardingFlowFeatureReminders: 'Rappels intelligents',
    onboardingFlowFeatureCurrency: 'Suivi de plusieurs devises',
    onboardingFlowStartTakingControl: 'Reprendre le contrôle',
    onboardingFlowPaywallHeadline: 'Sachez où va votre argent.',
    onboardingFlowPaywallSupport: 'Commencez à prendre les habitudes financières que vous souhaitez.',
    onboardingFlowPaywallGoalTemplate: 'Votre objectif : {goal}',
  },
  cs: {
    onboardingFlowEyebrow: 'VAŠE PENÍZE, VAŠÍ CESTOU',
    onboardingFlowQuestionProgress: 'Otázka {current} z {total}',
    onboardingFlowQ1Title: 'Co byste na svém přístupu k penězům chtěli změnit nejvíc?',
    onboardingFlowQ1Support: 'Vigil přizpůsobíme tomu, na čem vám nejvíc záleží.',
    onboardingFlowQ1Choices: 'Přestat přemýšlet, kam se poděly mé peníze|Utrácet méně bez pocitu, že se omezuji|Spořit pravidelněji|Mít své finance pod kontrolou|Vytvořit si lepší finanční návyky',
    onboardingFlowQ2Title: 'Co vás právě teď nejvíc frustruje?',
    onboardingFlowQ2Choices: 'Mám pocit, že peníze mizí příliš rychle|Utrácím víc, než si uvědomuji|Sledování výdajů vyžaduje příliš mnoho úsilí|Nedaří se mi držet rozpočet|Vím, že bych mohl/a více spořit',
    onboardingFlowQ3Title: 'Jak se obvykle cítíte, když nevíte, kam vaše peníze odešly?',
    onboardingFlowQ3Support: 'Neexistuje správná ani špatná odpověď.',
    onboardingFlowQ3Choices: 'Ve stresu|Frustrovaně|Mám výčitky|Mimo kontrolu|Většinou se tomu raději vyhýbám',
    onboardingFlowQ4Title: 'Jak často kontrolujete, kam vaše peníze skutečně odešly?',
    onboardingFlowQ4Choices: 'Každý den|Několikrát týdně|Občas|Obvykle až když peníze docházejí|Téměř nikdy',
    onboardingFlowQ5Title: 'Co vám obvykle brání sledovat své výdaje?',
    onboardingFlowQ5Choices: 'Zabere to příliš času|Zapomínám|Nechci všechno zadávat ručně|Ostatní aplikace mi připadají složité|Začnu, ale nevydržím u toho',
    onboardingFlowQ6Title: 'Představte si, že přesně víte, kam vaše peníze jdou, aniž byste na to museli pořád myslet. Co by vám to přineslo?',
    onboardingFlowQ6Choices: 'Klid|Více úspor|Větší kontrolu|Jistotu při utrácení|Pokrok směrem k mým cílům',
    onboardingFlowGoalPhrases: 'přestat řešit, kam se mé peníze poděly|utrácet méně bez pocitu omezení|spořit pravidelněji|mít své finance pod kontrolou|vytvořit si lepší finanční návyky',
    onboardingFlowFrictionPhrases: 'sledování výdajů zabírá příliš času|často na to zapomenete|ruční zapisování každého výdaje je příliš náročné|ostatní aplikace působí složitě|je těžké u toho vydržet',
    onboardingFlowReliefTitle: 'Vigil vám může pomoct se k tomu přiblížit.',
    onboardingFlowReliefTemplate: 'Řekli jste nám, že chcete {goal}, ale {friction}. Vigil vám má usnadnit přehled o penězích.',
    onboardingFlowReliefBenefitsTitle: 'S Vigilem můžete:',
    onboardingFlowReliefBenefit1: 'Zaznamenávat výdaje bez zdlouhavého ručního zadávání',
    onboardingFlowReliefBenefit2: 'Vidět, kam vaše peníze skutečně odcházejí',
    onboardingFlowReliefBenefit3: 'Snadněji rozpoznat své výdajové návyky',
    onboardingFlowReliefBenefit4: 'Plánovat výdaje a úspory s větší jistotou',
    onboardingFlowBuildPlan: 'Vytvořit můj plán',
    onboardingFlowTransition1: 'Seznamujeme se s vašimi cíli…',
    onboardingFlowTransition2: 'Zjišťujeme, co vám stojí v cestě…',
    onboardingFlowTransition3: 'Přizpůsobujeme Vigil vašim potřebám…',
    onboardingFlowResultEyebrow: 'PODLE TOHO, CO JSTE NÁM ŘEKLI',
    onboardingFlowResultTitle: 'Váš plán ve Vigil je připraven.',
    onboardingFlowResultTemplate: 'Chcete {goal}, ale {friction}. Vigil spojuje vaše finanční nástroje na jednom přehledném místě.',
    onboardingFlowFeatureVoice: 'Zaznamenávání výdajů hlasem',
    onboardingFlowFeatureReceipt: 'Skenování účtenek',
    onboardingFlowFeatureBank: 'Import bankovních snímků obrazovky',
    onboardingFlowFeatureInsights: 'Přehledy o výdajích',
    onboardingFlowFeaturePlanning: 'Plánování příjmů a výdajů',
    onboardingFlowFeatureReminders: 'Chytré připomínky',
    onboardingFlowFeatureCurrency: 'Sledování více měn',
    onboardingFlowStartTakingControl: 'Začít mít finance pod kontrolou',
    onboardingFlowPaywallHeadline: 'Mějte přehled, kam peníze jdou.',
    onboardingFlowPaywallSupport: 'Začněte budovat finanční návyky, které jste si přáli.',
    onboardingFlowPaywallGoalTemplate: 'Váš cíl: {goal}',
  },
  de: {
    onboardingFlowEyebrow: 'DEIN GELD, DEIN WEG',
    onboardingFlowQuestionProgress: 'Frage {current} von {total}',
    onboardingFlowQ1Title: 'Was möchtest du an deinem Umgang mit Geld am liebsten ändern?',
    onboardingFlowQ1Support: 'Wir richten Vigil danach aus, was dir am wichtigsten ist.',
    onboardingFlowQ1Choices: 'Nicht mehr rätseln, wohin mein Geld verschwunden ist|Weniger ausgeben, ohne mich eingeschränkt zu fühlen|Regelmäßiger sparen|Meine Finanzen besser im Griff haben|Bessere Geldgewohnheiten entwickeln',
    onboardingFlowQ2Title: 'Was frustriert dich gerade am meisten?',
    onboardingFlowQ2Choices: 'Mein Geld ist viel zu schnell weg|Ich gebe mehr aus, als mir bewusst ist|Ausgaben zu erfassen kostet zu viel Mühe|Es fällt mir schwer, mich an ein Budget zu halten|Ich weiß, dass ich mehr sparen könnte',
    onboardingFlowQ3Title: 'Wie fühlst du dich normalerweise, wenn du nicht weißt, wohin dein Geld geflossen ist?',
    onboardingFlowQ3Support: 'Es gibt keine richtige oder falsche Antwort.',
    onboardingFlowQ3Choices: 'Gestresst|Frustriert|Schuldig|Außer Kontrolle|Ich vermeide es meistens, darüber nachzudenken',
    onboardingFlowQ4Title: 'Wie oft prüfst du, wohin dein Geld tatsächlich geflossen ist?',
    onboardingFlowQ4Choices: 'Jeden Tag|Ein paar Mal pro Woche|Gelegentlich|Meistens erst, wenn das Geld knapp wird|Fast nie',
    onboardingFlowQ5Title: 'Was hält dich meistens davon ab, deine Ausgaben zu erfassen?',
    onboardingFlowQ5Choices: 'Es kostet zu viel Zeit|Ich vergesse es|Ich möchte nicht alles von Hand eingeben|Andere Apps wirken kompliziert|Ich fange an, bleibe aber nicht dabei',
    onboardingFlowQ6Title: 'Stell dir vor, du wüsstest genau, wohin dein Geld geht, ohne ständig daran denken zu müssen. Was würde dir das geben?',
    onboardingFlowQ6Choices: 'Mehr Ruhe|Mehr Ersparnisse|Mehr Kontrolle|Sicherheit beim Ausgeben|Fortschritt bei meinen Zielen',
    onboardingFlowGoalPhrases: 'nicht mehr rätseln, wohin mein Geld verschwunden ist|weniger ausgeben, ohne mich eingeschränkt zu fühlen|regelmäßiger sparen|meine Finanzen besser im Griff haben|bessere Geldgewohnheiten entwickeln',
    onboardingFlowFrictionPhrases: 'das Erfassen deiner Ausgaben kostet zu viel Zeit|du vergisst es|jede Ausgabe von Hand einzutragen ist dir zu mühsam|andere Apps wirken kompliziert|es fällt dir schwer, dranzubleiben',
    onboardingFlowReliefTitle: 'Vigil kann dir dabei helfen.',
    onboardingFlowReliefTemplate: 'Du möchtest {goal}, aber {friction}. Vigil soll es dir leichter machen, den Überblick über dein Geld zu behalten.',
    onboardingFlowReliefBenefitsTitle: 'Mit Vigil kannst du:',
    onboardingFlowReliefBenefit1: 'Ausgaben erfassen, ohne alles mühsam von Hand einzutragen',
    onboardingFlowReliefBenefit2: 'Sehen, wohin dein Geld tatsächlich fließt',
    onboardingFlowReliefBenefit3: 'Ausgabemuster leichter erkennen',
    onboardingFlowReliefBenefit4: 'Ausgaben und Ersparnisse sicherer planen',
    onboardingFlowBuildPlan: 'Meinen Plan erstellen',
    onboardingFlowTransition1: 'Wir ordnen deine Ziele…',
    onboardingFlowTransition2: 'Wir erkennen, was dich aufhält…',
    onboardingFlowTransition3: 'Wir richten Vigil auf dich aus…',
    onboardingFlowResultEyebrow: 'AUF DEINE ANGABEN ABGESTIMMT',
    onboardingFlowResultTitle: 'Dein Vigil-Plan ist fertig.',
    onboardingFlowResultTemplate: 'Du möchtest {goal}, aber {friction}. Vigil bündelt deine Geldtools an einem übersichtlichen Ort für den Anfang.',
    onboardingFlowFeatureVoice: 'Ausgaben per Sprache erfassen',
    onboardingFlowFeatureReceipt: 'Belege scannen',
    onboardingFlowFeatureBank: 'Screenshots von Bankumsätzen importieren',
    onboardingFlowFeatureInsights: 'Einblicke in deine Ausgaben',
    onboardingFlowFeaturePlanning: 'Einnahmen und Ausgaben planen',
    onboardingFlowFeatureReminders: 'Smarte Erinnerungen',
    onboardingFlowFeatureCurrency: 'Mehrere Währungen verfolgen',
    onboardingFlowStartTakingControl: 'Mehr Kontrolle gewinnen',
    onboardingFlowPaywallHeadline: 'Sieh, wohin dein Geld geht.',
    onboardingFlowPaywallSupport: 'Baue die Geldgewohnheiten auf, die du dir wünschst.',
    onboardingFlowPaywallGoalTemplate: 'Dein Ziel: {goal}',
  },
  es: {
    onboardingFlowEyebrow: 'TU DINERO, A TU MANERA',
    onboardingFlowQuestionProgress: 'Pregunta {current} de {total}',
    onboardingFlowQ1Title: '¿Qué te gustaría cambiar más de tu relación con el dinero?',
    onboardingFlowQ1Support: 'Adaptaremos Vigil a lo que más te importa.',
    onboardingFlowQ1Choices: 'Dejar de preguntarme adónde se fue mi dinero|Gastar menos sin sentir que me privo|Ahorrar con más constancia|Tener más control de mis finanzas|Crear mejores hábitos financieros',
    onboardingFlowQ2Title: '¿Qué es lo que más te frustra ahora mismo?',
    onboardingFlowQ2Choices: 'Siento que el dinero se me va demasiado rápido|Gasto más de lo que me doy cuenta|Registrar los gastos requiere demasiado esfuerzo|Me cuesta ceñirme a un presupuesto|Sé que podría ahorrar más',
    onboardingFlowQ3Title: 'Cuando no sabes adónde fue tu dinero, ¿cómo sueles sentirte?',
    onboardingFlowQ3Support: 'No hay respuestas correctas ni incorrectas.',
    onboardingFlowQ3Choices: 'Con estrés|Frustrado/a|Con culpa|Sin control|Suelo evitar pensar en ello',
    onboardingFlowQ4Title: '¿Con qué frecuencia revisas adónde fue realmente tu dinero?',
    onboardingFlowQ4Choices: 'Todos los días|Unas cuantas veces por semana|De vez en cuando|Normalmente cuando el dinero escasea|Casi nunca',
    onboardingFlowQ5Title: '¿Qué suele impedirte registrar tus gastos?',
    onboardingFlowQ5Choices: 'Lleva demasiado tiempo|Se me olvida|No me gusta introducirlo todo manualmente|Otras aplicaciones me parecen complicadas|Empiezo, pero no mantengo la constancia',
    onboardingFlowQ6Title: 'Imagina saber exactamente adónde va tu dinero sin tener que pensar en ello todo el tiempo. ¿Qué te aportaría?',
    onboardingFlowQ6Choices: 'Tranquilidad|Más ahorros|Más control|Confianza al gastar|Avanzar hacia mis objetivos',
    onboardingFlowGoalPhrases: 'dejar de preguntarme adónde se fue mi dinero|gastar menos sin sentir que me privo|ahorrar con más constancia|tener más control de mis finanzas|crear mejores hábitos financieros',
    onboardingFlowFrictionPhrases: 'registrar los gastos requiere demasiado esfuerzo|se te olvida hacerlo|introducir cada gasto a mano te resulta demasiado pesado|otras aplicaciones te parecen complicadas|te cuesta mantener la constancia',
    onboardingFlowReliefTitle: 'Vigil puede ayudarte a conseguirlo.',
    onboardingFlowReliefTemplate: 'Nos dijiste que quieres {goal}, pero {friction}. Vigil está pensado para que te resulte más fácil estar al tanto de tu dinero.',
    onboardingFlowReliefBenefitsTitle: 'Con Vigil puedes:',
    onboardingFlowReliefBenefit1: 'Registrar gastos sin tener que anotarlo todo a mano',
    onboardingFlowReliefBenefit2: 'Ver adónde va realmente tu dinero',
    onboardingFlowReliefBenefit3: 'Detectar patrones de gasto con más facilidad',
    onboardingFlowReliefBenefit4: 'Planificar gastos y ahorros con más confianza',
    onboardingFlowBuildPlan: 'Crear mi plan',
    onboardingFlowTransition1: 'Entendiendo tus objetivos…',
    onboardingFlowTransition2: 'Identificando lo que se interpone…',
    onboardingFlowTransition3: 'Personalizando tu experiencia en Vigil…',
    onboardingFlowResultEyebrow: 'A PARTIR DE LO QUE NOS CONTASTE',
    onboardingFlowResultTitle: 'Tu plan de Vigil está listo.',
    onboardingFlowResultTemplate: 'Quieres {goal}, pero {friction}. Vigil reúne tus herramientas de dinero en un lugar sencillo para empezar.',
    onboardingFlowFeatureVoice: 'Registro de gastos por voz',
    onboardingFlowFeatureReceipt: 'Escaneo de recibos',
    onboardingFlowFeatureBank: 'Importación de capturas bancarias',
    onboardingFlowFeatureInsights: 'Análisis de gastos',
    onboardingFlowFeaturePlanning: 'Planificación de ingresos y gastos',
    onboardingFlowFeatureReminders: 'Recordatorios inteligentes',
    onboardingFlowFeatureCurrency: 'Seguimiento de varias divisas',
    onboardingFlowStartTakingControl: 'Empieza a tomar el control',
    onboardingFlowPaywallHeadline: 'Ten claro adónde va tu dinero.',
    onboardingFlowPaywallSupport: 'Empieza a crear los hábitos financieros que quieres tener.',
    onboardingFlowPaywallGoalTemplate: 'Tu objetivo: {goal}',
  },
  ru: {
    onboardingFlowEyebrow: 'ВАШИ ДЕНЬГИ — ВАШИ ПРАВИЛА',
    onboardingFlowQuestionProgress: 'Вопрос {current} из {total}',
    onboardingFlowQ1Title: 'Что вам больше всего хотелось бы изменить в обращении с деньгами?',
    onboardingFlowQ1Support: 'Мы настроим Vigil с учётом того, что важно именно вам.',
    onboardingFlowQ1Choices: 'Перестать гадать, куда ушли деньги|Тратить меньше и не чувствовать себя ущемлённо|Откладывать деньги регулярнее|Лучше контролировать свои финансы|Выработать полезные финансовые привычки',
    onboardingFlowQ2Title: 'Что больше всего расстраивает вас сейчас?',
    onboardingFlowQ2Choices: 'Деньги заканчиваются слишком быстро|Я трачу больше, чем замечаю|Отслеживание расходов требует слишком много усилий|Мне трудно придерживаться бюджета|Я знаю, что мог(ла) бы откладывать больше',
    onboardingFlowQ3Title: 'Что вы обычно чувствуете, когда не знаете, куда ушли деньги?',
    onboardingFlowQ3Support: 'Здесь нет правильных или неправильных ответов.',
    onboardingFlowQ3Choices: 'Стресс|Раздражение|Чувство вины|Потерю контроля|Чаще всего стараюсь об этом не думать',
    onboardingFlowQ4Title: 'Как часто вы проверяете, куда на самом деле ушли деньги?',
    onboardingFlowQ4Choices: 'Каждый день|Несколько раз в неделю|Иногда|Обычно, когда денег становится мало|Почти никогда',
    onboardingFlowQ5Title: 'Что обычно мешает вам отслеживать расходы?',
    onboardingFlowQ5Choices: 'Это занимает слишком много времени|Я забываю|Мне не нравится вносить всё вручную|Другие приложения кажутся сложными|Я начинаю, но не могу продолжать регулярно',
    onboardingFlowQ6Title: 'Представьте, что вы точно знаете, куда уходят деньги, и вам не нужно постоянно об этом думать. Что это вам даст?',
    onboardingFlowQ6Choices: 'Спокойствие|Больше сбережений|Больше контроля|Уверенность при тратах|Продвижение к моим целям',
    onboardingFlowGoalPhrases: 'перестать гадать, куда уходят деньги|тратить меньше без ощущения ограничений|регулярнее откладывать деньги|лучше контролировать свои финансы|сформировать полезные финансовые привычки',
    onboardingFlowFrictionPhrases: 'отслеживание расходов отнимает слишком много времени|вы забываете об этом|вносить каждую покупку вручную утомительно|другие приложения кажутся сложными|вам трудно придерживаться этого регулярно',
    onboardingFlowReliefTitle: 'Vigil поможет вам двигаться к этой цели.',
    onboardingFlowReliefTemplate: 'Вы рассказали, что хотите {goal}, но {friction}. Vigil создан, чтобы вам было проще следить за своими деньгами.',
    onboardingFlowReliefBenefitsTitle: 'С Vigil вы сможете:',
    onboardingFlowReliefBenefit1: 'Записывать расходы без утомительного ручного ввода',
    onboardingFlowReliefBenefit2: 'Видеть, куда на самом деле уходят деньги',
    onboardingFlowReliefBenefit3: 'Легче замечать привычки в расходах',
    onboardingFlowReliefBenefit4: 'Увереннее планировать расходы и сбережения',
    onboardingFlowBuildPlan: 'Составить мой план',
    onboardingFlowTransition1: 'Уточняем ваши цели…',
    onboardingFlowTransition2: 'Определяем, что мешает…',
    onboardingFlowTransition3: 'Настраиваем Vigil под вас…',
    onboardingFlowResultEyebrow: 'С УЧЁТОМ ВАШИХ ОТВЕТОВ',
    onboardingFlowResultTitle: 'Ваш план Vigil готов.',
    onboardingFlowResultTemplate: 'Вы хотите {goal}, но {friction}. Vigil объединяет финансовые инструменты в одном понятном месте, с которого удобно начать.',
    onboardingFlowFeatureVoice: 'Добавление расходов голосом',
    onboardingFlowFeatureReceipt: 'Сканирование чеков',
    onboardingFlowFeatureBank: 'Импорт снимков экрана из банка',
    onboardingFlowFeatureInsights: 'Анализ расходов',
    onboardingFlowFeaturePlanning: 'Планирование доходов и расходов',
    onboardingFlowFeatureReminders: 'Умные напоминания',
    onboardingFlowFeatureCurrency: 'Учёт нескольких валют',
    onboardingFlowStartTakingControl: 'Начать управлять деньгами',
    onboardingFlowPaywallHeadline: 'Знайте, куда уходят деньги.',
    onboardingFlowPaywallSupport: 'Начните формировать полезные денежные привычки, которых вы хотите.',
    onboardingFlowPaywallGoalTemplate: 'Ваша цель: {goal}',
  },
  ar: {
    onboardingFlowEyebrow: 'أموالك، بالطريقة التي تناسبك',
    onboardingFlowQuestionProgress: 'السؤال {current} من {total}',
    onboardingFlowQ1Title: 'ما أكثر ما ترغب في تغييره في طريقة تعاملك مع المال؟',
    onboardingFlowQ1Support: 'سنخصّص Vigil بما يناسب أكثر ما يهمك.',
    onboardingFlowQ1Choices: 'أن أتوقف عن التساؤل أين ذهب مالي|أن أنفق أقل من دون أن أشعر بالحرمان|أن أدّخر بانتظام أكثر|أن أتحكم في أموري المالية|أن أبني عادات مالية أفضل',
    onboardingFlowQ2Title: 'ما أكثر ما يزعجك الآن؟',
    onboardingFlowQ2Choices: 'أشعر أن مالي ينفد بسرعة|أنفق أكثر مما أظن|متابعة المصروفات تتطلب جهداً كبيراً|أجد صعوبة في الالتزام بالميزانية|أعرف أن بإمكاني ادخار المزيد',
    onboardingFlowQ3Title: 'عندما لا تعرف أين ذهب مالك، كيف تشعر غالباً؟',
    onboardingFlowQ3Support: 'لا توجد إجابة صحيحة أو خاطئة.',
    onboardingFlowQ3Choices: 'بالتوتر|بالإحباط|بالذنب|بأن الأمور خارجة عن سيطرتي|غالباً ما أتجنب التفكير في الأمر',
    onboardingFlowQ4Title: 'كم مرة تتحقق مما حدث لمالك فعلياً؟',
    onboardingFlowQ4Choices: 'كل يوم|عدة مرات في الأسبوع|أحياناً|عادةً عندما يضيق المال|نادراً جداً',
    onboardingFlowQ5Title: 'ما الذي يمنعك عادةً من تتبع إنفاقك؟',
    onboardingFlowQ5Choices: 'يستغرق وقتاً طويلاً|أنسى|لا أحب إدخال كل شيء يدوياً|التطبيقات الأخرى تبدو معقدة|أبدأ لكن يصعب عليّ الاستمرار',
    onboardingFlowQ6Title: 'تخيّل أنك تعرف أين يذهب مالك بالضبط من دون أن تفكر في الأمر باستمرار. ماذا سيمنحك ذلك؟',
    onboardingFlowQ6Choices: 'راحة البال|مدخرات أكثر|تحكماً أكبر|ثقة أكبر عند الإنفاق|تقدماً نحو أهدافي',
    onboardingFlowGoalPhrases: 'ألا تتساءل أين ذهب مالك|أن تنفق أقل من دون شعور بالحرمان|أن تدّخر بانتظام أكثر|أن تتحكم في شؤونك المالية|أن تبني عادات مالية أفضل',
    onboardingFlowFrictionPhrases: 'متابعة المصروفات تستغرق وقتاً وجهداً كبيرين|تنسى تسجيل مصروفاتك|إدخال كل عملية يدوياً مرهق لك|التطبيقات الأخرى تبدو معقدة|يصعب عليك الاستمرار بانتظام',
    onboardingFlowReliefTitle: 'يمكن لـ Vigil مساعدتك على الوصول إلى ذلك.',
    onboardingFlowReliefTemplate: 'أخبرتنا أنك تريد {goal}، لكن {friction}. صُمّم Vigil ليساعدك على متابعة أموالك بسهولة أكبر.',
    onboardingFlowReliefBenefitsTitle: 'مع Vigil، يمكنك:',
    onboardingFlowReliefBenefit1: 'تسجيل المصروفات من دون إدخال كل شيء يدوياً',
    onboardingFlowReliefBenefit2: 'معرفة أين تذهب أموالك فعلياً',
    onboardingFlowReliefBenefit3: 'ملاحظة أنماط الإنفاق بسهولة أكبر',
    onboardingFlowReliefBenefit4: 'التخطيط للإنفاق والادخار بثقة أكبر',
    onboardingFlowBuildPlan: 'أنشئ خطتي',
    onboardingFlowTransition1: 'نتعرّف على أهدافك…',
    onboardingFlowTransition2: 'نحدّد ما يقف في طريقك…',
    onboardingFlowTransition3: 'نخصّص تجربة Vigil لك…',
    onboardingFlowResultEyebrow: 'وفقاً لما أخبرتنا به',
    onboardingFlowResultTitle: 'خطتك في Vigil جاهزة.',
    onboardingFlowResultTemplate: 'تريد {goal}، لكن {friction}. يجمع Vigil أدواتك المالية في مكان أبسط لتبدأ منه.',
    onboardingFlowFeatureVoice: 'تسجيل المصروفات بالصوت',
    onboardingFlowFeatureReceipt: 'مسح الإيصالات',
    onboardingFlowFeatureBank: 'استيراد لقطات شاشة البنك',
    onboardingFlowFeatureInsights: 'رؤى حول الإنفاق',
    onboardingFlowFeaturePlanning: 'التخطيط للدخل والإنفاق',
    onboardingFlowFeatureReminders: 'تذكيرات ذكية',
    onboardingFlowFeatureCurrency: 'تتبع عدة عملات',
    onboardingFlowStartTakingControl: 'ابدأ بإدارة أموالك',
    onboardingFlowPaywallHeadline: 'اعرف أين تذهب أموالك.',
    onboardingFlowPaywallSupport: 'ابدأ ببناء العادات المالية التي أخبرتنا أنك تريدها.',
    onboardingFlowPaywallGoalTemplate: 'هدفك: {goal}',
  },
};

export function getOnboardingFlowMessage(
  language: SupportedLanguage,
  key: string,
): string | undefined {
  return onboardingFlowCopy[language][key as OnboardingFlowCopyKey];
}